/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AirParameter = { 'CO' : null } |
  { 'NOx' : null } |
  { 'SO2' : null } |
  { 'PM10' : null } |
  { 'PM2_5' : null } |
  { 'Other' : string };
export interface AirQualityReading {
  'id' : AirReadingId,
  'measuredBy' : string,
  'value' : number,
  'date' : Timestamp,
  'parameter' : AirParameter,
  'createdAt' : Timestamp,
  'unit' : string,
  'notes' : string,
  'location' : string,
}
export type AirReadingId = bigint;
export interface ComplianceTask {
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : string,
  'responsibleOfficer' : string,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'conditionText' : string,
  'taskType' : TaskType,
  'updatedAt' : Timestamp,
  'notes' : string,
}
export interface CreateAirReadingRequest {
  'measuredBy' : string,
  'value' : number,
  'date' : Timestamp,
  'parameter' : AirParameter,
  'unit' : string,
  'notes' : string,
  'location' : string,
}
export interface CreatePiezoReadingRequest {
  'pH' : number,
  'wellId' : string,
  'measuredBy' : string,
  'turbidity' : number,
  'date' : Timestamp,
  'notes' : string,
  'conductivity' : number,
  'depthToWater' : number,
  'location' : string,
}
export interface CreateTaskRequest {
  'title' : string,
  'responsibleOfficer' : string,
  'dueDate' : Timestamp,
  'conditionText' : string,
  'taskType' : TaskType,
  'notes' : string,
}
export interface CreateTreeRecordRequest {
  'plantingDate' : Timestamp,
  'plantedBy' : string,
  'count' : bigint,
  'notes' : string,
  'species' : string,
  'location' : string,
}
export interface DashboardStats {
  'recentAirReadingsCount' : bigint,
  'taskCounts' : TaskStatusCounts,
  'totalTreesPlanted' : bigint,
  'recentPiezoReadingsCount' : bigint,
}
export type PiezoReadingId = bigint;
export interface PiezometerReading {
  'id' : PiezoReadingId,
  'pH' : number,
  'wellId' : string,
  'measuredBy' : string,
  'turbidity' : number,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : string,
  'conductivity' : number,
  'depthToWater' : number,
  'location' : string,
}
export interface SpeciesSummary { 'totalCount' : bigint, 'species' : string }
export type TaskId = bigint;
export type TaskStatus = { 'Overdue' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface TaskStatusCounts {
  'pending' : bigint,
  'completed' : bigint,
  'overdue' : bigint,
  'inProgress' : bigint,
}
export type TaskType = { 'EC' : null } |
  { 'CTE' : null } |
  { 'CTO' : null };
export type Timestamp = bigint;
export interface TreeRecord {
  'id' : TreeRecordId,
  'plantingDate' : Timestamp,
  'plantedBy' : string,
  'createdAt' : Timestamp,
  'count' : bigint,
  'notes' : string,
  'species' : string,
  'location' : string,
}
export type TreeRecordId = bigint;
export interface UpdateTaskRequest { 'status' : TaskStatus, 'notes' : string }
export interface _SERVICE {
  'addAirQualityReading' : ActorMethod<
    [CreateAirReadingRequest],
    AirQualityReading
  >,
  'addPiezometerReading' : ActorMethod<
    [CreatePiezoReadingRequest],
    PiezometerReading
  >,
  'addTreeRecord' : ActorMethod<[CreateTreeRecordRequest], TreeRecord>,
  'createComplianceTask' : ActorMethod<[CreateTaskRequest], ComplianceTask>,
  'deleteAirQualityReading' : ActorMethod<[AirReadingId], boolean>,
  'deleteComplianceTask' : ActorMethod<[TaskId], boolean>,
  'deletePiezometerReading' : ActorMethod<[PiezoReadingId], boolean>,
  'deleteTreeRecord' : ActorMethod<[TreeRecordId], boolean>,
  'getComplianceTask' : ActorMethod<[TaskId], [] | [ComplianceTask]>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getTreeSpeciesSummary' : ActorMethod<[], Array<SpeciesSummary>>,
  'listAirQualityReadings' : ActorMethod<[], Array<AirQualityReading>>,
  'listAirQualityReadingsInRange' : ActorMethod<
    [Timestamp, Timestamp],
    Array<AirQualityReading>
  >,
  'listComplianceTasks' : ActorMethod<[], Array<ComplianceTask>>,
  'listComplianceTasksByStatus' : ActorMethod<
    [TaskStatus],
    Array<ComplianceTask>
  >,
  'listPiezometerReadings' : ActorMethod<[], Array<PiezometerReading>>,
  'listTreeRecords' : ActorMethod<[], Array<TreeRecord>>,
  'updateComplianceTask' : ActorMethod<
    [TaskId, UpdateTaskRequest],
    [] | [ComplianceTask]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];