/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const AirParameter = IDL.Variant({
  'CO' : IDL.Null,
  'NOx' : IDL.Null,
  'SO2' : IDL.Null,
  'PM10' : IDL.Null,
  'PM2_5' : IDL.Null,
  'Other' : IDL.Text,
});
export const CreateAirReadingRequest = IDL.Record({
  'measuredBy' : IDL.Text,
  'value' : IDL.Float64,
  'date' : Timestamp,
  'parameter' : AirParameter,
  'unit' : IDL.Text,
  'notes' : IDL.Text,
  'location' : IDL.Text,
});
export const AirReadingId = IDL.Nat;
export const AirQualityReading = IDL.Record({
  'id' : AirReadingId,
  'measuredBy' : IDL.Text,
  'value' : IDL.Float64,
  'date' : Timestamp,
  'parameter' : AirParameter,
  'createdAt' : Timestamp,
  'unit' : IDL.Text,
  'notes' : IDL.Text,
  'location' : IDL.Text,
});
export const CreatePiezoReadingRequest = IDL.Record({
  'pH' : IDL.Float64,
  'wellId' : IDL.Text,
  'measuredBy' : IDL.Text,
  'turbidity' : IDL.Float64,
  'date' : Timestamp,
  'notes' : IDL.Text,
  'conductivity' : IDL.Float64,
  'depthToWater' : IDL.Float64,
  'location' : IDL.Text,
});
export const PiezoReadingId = IDL.Nat;
export const PiezometerReading = IDL.Record({
  'id' : PiezoReadingId,
  'pH' : IDL.Float64,
  'wellId' : IDL.Text,
  'measuredBy' : IDL.Text,
  'turbidity' : IDL.Float64,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
  'conductivity' : IDL.Float64,
  'depthToWater' : IDL.Float64,
  'location' : IDL.Text,
});
export const CreateTreeRecordRequest = IDL.Record({
  'plantingDate' : Timestamp,
  'plantedBy' : IDL.Text,
  'count' : IDL.Nat,
  'notes' : IDL.Text,
  'species' : IDL.Text,
  'location' : IDL.Text,
});
export const TreeRecordId = IDL.Nat;
export const TreeRecord = IDL.Record({
  'id' : TreeRecordId,
  'plantingDate' : Timestamp,
  'plantedBy' : IDL.Text,
  'createdAt' : Timestamp,
  'count' : IDL.Nat,
  'notes' : IDL.Text,
  'species' : IDL.Text,
  'location' : IDL.Text,
});
export const TaskType = IDL.Variant({
  'EC' : IDL.Null,
  'CTE' : IDL.Null,
  'CTO' : IDL.Null,
});
export const CreateTaskRequest = IDL.Record({
  'title' : IDL.Text,
  'responsibleOfficer' : IDL.Text,
  'dueDate' : Timestamp,
  'conditionText' : IDL.Text,
  'taskType' : TaskType,
  'notes' : IDL.Text,
});
export const TaskId = IDL.Nat;
export const TaskStatus = IDL.Variant({
  'Overdue' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ComplianceTask = IDL.Record({
  'id' : TaskId,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'responsibleOfficer' : IDL.Text,
  'createdAt' : Timestamp,
  'dueDate' : Timestamp,
  'conditionText' : IDL.Text,
  'taskType' : TaskType,
  'updatedAt' : Timestamp,
  'notes' : IDL.Text,
});
export const TaskStatusCounts = IDL.Record({
  'pending' : IDL.Nat,
  'completed' : IDL.Nat,
  'overdue' : IDL.Nat,
  'inProgress' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'recentAirReadingsCount' : IDL.Nat,
  'taskCounts' : TaskStatusCounts,
  'totalTreesPlanted' : IDL.Nat,
  'recentPiezoReadingsCount' : IDL.Nat,
});
export const SpeciesSummary = IDL.Record({
  'totalCount' : IDL.Nat,
  'species' : IDL.Text,
});
export const UpdateTaskRequest = IDL.Record({
  'status' : TaskStatus,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAirQualityReading' : IDL.Func(
      [CreateAirReadingRequest],
      [AirQualityReading],
      [],
    ),
  'addPiezometerReading' : IDL.Func(
      [CreatePiezoReadingRequest],
      [PiezometerReading],
      [],
    ),
  'addTreeRecord' : IDL.Func([CreateTreeRecordRequest], [TreeRecord], []),
  'createComplianceTask' : IDL.Func([CreateTaskRequest], [ComplianceTask], []),
  'deleteAirQualityReading' : IDL.Func([AirReadingId], [IDL.Bool], []),
  'deleteComplianceTask' : IDL.Func([TaskId], [IDL.Bool], []),
  'deletePiezometerReading' : IDL.Func([PiezoReadingId], [IDL.Bool], []),
  'deleteTreeRecord' : IDL.Func([TreeRecordId], [IDL.Bool], []),
  'getComplianceTask' : IDL.Func(
      [TaskId],
      [IDL.Opt(ComplianceTask)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getTreeSpeciesSummary' : IDL.Func([], [IDL.Vec(SpeciesSummary)], ['query']),
  'listAirQualityReadings' : IDL.Func(
      [],
      [IDL.Vec(AirQualityReading)],
      ['query'],
    ),
  'listAirQualityReadingsInRange' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(AirQualityReading)],
      ['query'],
    ),
  'listComplianceTasks' : IDL.Func([], [IDL.Vec(ComplianceTask)], ['query']),
  'listComplianceTasksByStatus' : IDL.Func(
      [TaskStatus],
      [IDL.Vec(ComplianceTask)],
      ['query'],
    ),
  'listPiezometerReadings' : IDL.Func(
      [],
      [IDL.Vec(PiezometerReading)],
      ['query'],
    ),
  'listTreeRecords' : IDL.Func([], [IDL.Vec(TreeRecord)], ['query']),
  'updateComplianceTask' : IDL.Func(
      [TaskId, UpdateTaskRequest],
      [IDL.Opt(ComplianceTask)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const AirParameter = IDL.Variant({
    'CO' : IDL.Null,
    'NOx' : IDL.Null,
    'SO2' : IDL.Null,
    'PM10' : IDL.Null,
    'PM2_5' : IDL.Null,
    'Other' : IDL.Text,
  });
  const CreateAirReadingRequest = IDL.Record({
    'measuredBy' : IDL.Text,
    'value' : IDL.Float64,
    'date' : Timestamp,
    'parameter' : AirParameter,
    'unit' : IDL.Text,
    'notes' : IDL.Text,
    'location' : IDL.Text,
  });
  const AirReadingId = IDL.Nat;
  const AirQualityReading = IDL.Record({
    'id' : AirReadingId,
    'measuredBy' : IDL.Text,
    'value' : IDL.Float64,
    'date' : Timestamp,
    'parameter' : AirParameter,
    'createdAt' : Timestamp,
    'unit' : IDL.Text,
    'notes' : IDL.Text,
    'location' : IDL.Text,
  });
  const CreatePiezoReadingRequest = IDL.Record({
    'pH' : IDL.Float64,
    'wellId' : IDL.Text,
    'measuredBy' : IDL.Text,
    'turbidity' : IDL.Float64,
    'date' : Timestamp,
    'notes' : IDL.Text,
    'conductivity' : IDL.Float64,
    'depthToWater' : IDL.Float64,
    'location' : IDL.Text,
  });
  const PiezoReadingId = IDL.Nat;
  const PiezometerReading = IDL.Record({
    'id' : PiezoReadingId,
    'pH' : IDL.Float64,
    'wellId' : IDL.Text,
    'measuredBy' : IDL.Text,
    'turbidity' : IDL.Float64,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
    'conductivity' : IDL.Float64,
    'depthToWater' : IDL.Float64,
    'location' : IDL.Text,
  });
  const CreateTreeRecordRequest = IDL.Record({
    'plantingDate' : Timestamp,
    'plantedBy' : IDL.Text,
    'count' : IDL.Nat,
    'notes' : IDL.Text,
    'species' : IDL.Text,
    'location' : IDL.Text,
  });
  const TreeRecordId = IDL.Nat;
  const TreeRecord = IDL.Record({
    'id' : TreeRecordId,
    'plantingDate' : Timestamp,
    'plantedBy' : IDL.Text,
    'createdAt' : Timestamp,
    'count' : IDL.Nat,
    'notes' : IDL.Text,
    'species' : IDL.Text,
    'location' : IDL.Text,
  });
  const TaskType = IDL.Variant({
    'EC' : IDL.Null,
    'CTE' : IDL.Null,
    'CTO' : IDL.Null,
  });
  const CreateTaskRequest = IDL.Record({
    'title' : IDL.Text,
    'responsibleOfficer' : IDL.Text,
    'dueDate' : Timestamp,
    'conditionText' : IDL.Text,
    'taskType' : TaskType,
    'notes' : IDL.Text,
  });
  const TaskId = IDL.Nat;
  const TaskStatus = IDL.Variant({
    'Overdue' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ComplianceTask = IDL.Record({
    'id' : TaskId,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'responsibleOfficer' : IDL.Text,
    'createdAt' : Timestamp,
    'dueDate' : Timestamp,
    'conditionText' : IDL.Text,
    'taskType' : TaskType,
    'updatedAt' : Timestamp,
    'notes' : IDL.Text,
  });
  const TaskStatusCounts = IDL.Record({
    'pending' : IDL.Nat,
    'completed' : IDL.Nat,
    'overdue' : IDL.Nat,
    'inProgress' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'recentAirReadingsCount' : IDL.Nat,
    'taskCounts' : TaskStatusCounts,
    'totalTreesPlanted' : IDL.Nat,
    'recentPiezoReadingsCount' : IDL.Nat,
  });
  const SpeciesSummary = IDL.Record({
    'totalCount' : IDL.Nat,
    'species' : IDL.Text,
  });
  const UpdateTaskRequest = IDL.Record({
    'status' : TaskStatus,
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    'addAirQualityReading' : IDL.Func(
        [CreateAirReadingRequest],
        [AirQualityReading],
        [],
      ),
    'addPiezometerReading' : IDL.Func(
        [CreatePiezoReadingRequest],
        [PiezometerReading],
        [],
      ),
    'addTreeRecord' : IDL.Func([CreateTreeRecordRequest], [TreeRecord], []),
    'createComplianceTask' : IDL.Func(
        [CreateTaskRequest],
        [ComplianceTask],
        [],
      ),
    'deleteAirQualityReading' : IDL.Func([AirReadingId], [IDL.Bool], []),
    'deleteComplianceTask' : IDL.Func([TaskId], [IDL.Bool], []),
    'deletePiezometerReading' : IDL.Func([PiezoReadingId], [IDL.Bool], []),
    'deleteTreeRecord' : IDL.Func([TreeRecordId], [IDL.Bool], []),
    'getComplianceTask' : IDL.Func(
        [TaskId],
        [IDL.Opt(ComplianceTask)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getTreeSpeciesSummary' : IDL.Func(
        [],
        [IDL.Vec(SpeciesSummary)],
        ['query'],
      ),
    'listAirQualityReadings' : IDL.Func(
        [],
        [IDL.Vec(AirQualityReading)],
        ['query'],
      ),
    'listAirQualityReadingsInRange' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(AirQualityReading)],
        ['query'],
      ),
    'listComplianceTasks' : IDL.Func([], [IDL.Vec(ComplianceTask)], ['query']),
    'listComplianceTasksByStatus' : IDL.Func(
        [TaskStatus],
        [IDL.Vec(ComplianceTask)],
        ['query'],
      ),
    'listPiezometerReadings' : IDL.Func(
        [],
        [IDL.Vec(PiezometerReading)],
        ['query'],
      ),
    'listTreeRecords' : IDL.Func([], [IDL.Vec(TreeRecord)], ['query']),
    'updateComplianceTask' : IDL.Func(
        [TaskId, UpdateTaskRequest],
        [IDL.Opt(ComplianceTask)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };