/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type TreeRecordId = bigint;
export interface PiezometerReading {
    id: PiezoReadingId;
    pH: number;
    wellId: string;
    measuredBy: string;
    turbidity: number;
    date: Timestamp;
    createdAt: Timestamp;
    notes: string;
    conductivity: number;
    depthToWater: number;
    location: string;
}
export interface CreateAirReadingRequest {
    measuredBy: string;
    value: number;
    date: Timestamp;
    parameter: AirParameter;
    unit: string;
    notes: string;
    location: string;
}
export interface CreateTaskRequest {
    title: string;
    responsibleOfficer: string;
    dueDate: Timestamp;
    conditionText: string;
    taskType: TaskType;
    notes: string;
}
export interface DashboardStats {
    recentAirReadingsCount: bigint;
    taskCounts: TaskStatusCounts;
    totalTreesPlanted: bigint;
    recentPiezoReadingsCount: bigint;
}
export interface CreatePiezoReadingRequest {
    pH: number;
    wellId: string;
    measuredBy: string;
    turbidity: number;
    date: Timestamp;
    notes: string;
    conductivity: number;
    depthToWater: number;
    location: string;
}
export interface TreeRecord {
    id: TreeRecordId;
    plantingDate: Timestamp;
    plantedBy: string;
    createdAt: Timestamp;
    count: bigint;
    notes: string;
    species: string;
    location: string;
}
export interface UpdateTaskRequest {
    status: TaskStatus;
    notes: string;
}
export interface CreateTreeRecordRequest {
    plantingDate: Timestamp;
    plantedBy: string;
    count: bigint;
    notes: string;
    species: string;
    location: string;
}
export type AirReadingId = bigint;
export type AirParameter = {
    __kind__: "CO";
    CO: null;
} | {
    __kind__: "NOx";
    NOx: null;
} | {
    __kind__: "SO2";
    SO2: null;
} | {
    __kind__: "PM10";
    PM10: null;
} | {
    __kind__: "PM2_5";
    PM2_5: null;
} | {
    __kind__: "Other";
    Other: string;
};
export type TaskId = bigint;
export interface SpeciesSummary {
    totalCount: bigint;
    species: string;
}
export interface TaskStatusCounts {
    pending: bigint;
    completed: bigint;
    overdue: bigint;
    inProgress: bigint;
}
export type PiezoReadingId = bigint;
export interface ComplianceTask {
    id: TaskId;
    status: TaskStatus;
    title: string;
    responsibleOfficer: string;
    createdAt: Timestamp;
    dueDate: Timestamp;
    conditionText: string;
    taskType: TaskType;
    updatedAt: Timestamp;
    notes: string;
}
export interface AirQualityReading {
    id: AirReadingId;
    measuredBy: string;
    value: number;
    date: Timestamp;
    parameter: AirParameter;
    createdAt: Timestamp;
    unit: string;
    notes: string;
    location: string;
}
export enum TaskStatus {
    Overdue = "Overdue",
    InProgress = "InProgress",
    Completed = "Completed",
    Pending = "Pending"
}
export enum TaskType {
    EC = "EC",
    CTE = "CTE",
    CTO = "CTO"
}
export interface backendInterface {
    addAirQualityReading(req: CreateAirReadingRequest): Promise<AirQualityReading>;
    addPiezometerReading(req: CreatePiezoReadingRequest): Promise<PiezometerReading>;
    addTreeRecord(req: CreateTreeRecordRequest): Promise<TreeRecord>;
    createComplianceTask(req: CreateTaskRequest): Promise<ComplianceTask>;
    deleteAirQualityReading(id: AirReadingId): Promise<boolean>;
    deleteComplianceTask(id: TaskId): Promise<boolean>;
    deletePiezometerReading(id: PiezoReadingId): Promise<boolean>;
    deleteTreeRecord(id: TreeRecordId): Promise<boolean>;
    getComplianceTask(id: TaskId): Promise<ComplianceTask | null>;
    getDashboardStats(): Promise<DashboardStats>;
    getTreeSpeciesSummary(): Promise<Array<SpeciesSummary>>;
    listAirQualityReadings(): Promise<Array<AirQualityReading>>;
    listAirQualityReadingsInRange(fromDate: Timestamp, toDate: Timestamp): Promise<Array<AirQualityReading>>;
    listComplianceTasks(): Promise<Array<ComplianceTask>>;
    listComplianceTasksByStatus(status: TaskStatus): Promise<Array<ComplianceTask>>;
    listPiezometerReadings(): Promise<Array<PiezometerReading>>;
    listTreeRecords(): Promise<Array<TreeRecord>>;
    updateComplianceTask(id: TaskId, req: UpdateTaskRequest): Promise<ComplianceTask | null>;
}
import type { AirParameter as _AirParameter, AirQualityReading as _AirQualityReading, AirReadingId as _AirReadingId, ComplianceTask as _ComplianceTask, CreateAirReadingRequest as _CreateAirReadingRequest, CreateTaskRequest as _CreateTaskRequest, TaskId as _TaskId, TaskStatus as _TaskStatus, TaskType as _TaskType, Timestamp as _Timestamp, UpdateTaskRequest as _UpdateTaskRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAirQualityReading(arg0: CreateAirReadingRequest): Promise<AirQualityReading> {
        if (this.processError) {
            try {
                const result = await this.actor.addAirQualityReading(to_candid_CreateAirReadingRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_AirQualityReading_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAirQualityReading(to_candid_CreateAirReadingRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_AirQualityReading_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPiezometerReading(arg0: CreatePiezoReadingRequest): Promise<PiezometerReading> {
        if (this.processError) {
            try {
                const result = await this.actor.addPiezometerReading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPiezometerReading(arg0);
            return result;
        }
    }
    async addTreeRecord(arg0: CreateTreeRecordRequest): Promise<TreeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addTreeRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTreeRecord(arg0);
            return result;
        }
    }
    async createComplianceTask(arg0: CreateTaskRequest): Promise<ComplianceTask> {
        if (this.processError) {
            try {
                const result = await this.actor.createComplianceTask(to_candid_CreateTaskRequest_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ComplianceTask_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComplianceTask(to_candid_CreateTaskRequest_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ComplianceTask_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAirQualityReading(arg0: AirReadingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAirQualityReading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAirQualityReading(arg0);
            return result;
        }
    }
    async deleteComplianceTask(arg0: TaskId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComplianceTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComplianceTask(arg0);
            return result;
        }
    }
    async deletePiezometerReading(arg0: PiezoReadingId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePiezometerReading(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePiezometerReading(arg0);
            return result;
        }
    }
    async deleteTreeRecord(arg0: TreeRecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTreeRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTreeRecord(arg0);
            return result;
        }
    }
    async getComplianceTask(arg0: TaskId): Promise<ComplianceTask | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getComplianceTask(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComplianceTask(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getTreeSpeciesSummary(): Promise<Array<SpeciesSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreeSpeciesSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreeSpeciesSummary();
            return result;
        }
    }
    async listAirQualityReadings(): Promise<Array<AirQualityReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAirQualityReadings();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAirQualityReadings();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAirQualityReadingsInRange(arg0: Timestamp, arg1: Timestamp): Promise<Array<AirQualityReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAirQualityReadingsInRange(arg0, arg1);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAirQualityReadingsInRange(arg0, arg1);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listComplianceTasks(): Promise<Array<ComplianceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComplianceTasks();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComplianceTasks();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listComplianceTasksByStatus(arg0: TaskStatus): Promise<Array<ComplianceTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComplianceTasksByStatus(to_candid_TaskStatus_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComplianceTasksByStatus(to_candid_TaskStatus_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPiezometerReadings(): Promise<Array<PiezometerReading>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPiezometerReadings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPiezometerReadings();
            return result;
        }
    }
    async listTreeRecords(): Promise<Array<TreeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTreeRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTreeRecords();
            return result;
        }
    }
    async updateComplianceTask(arg0: TaskId, arg1: UpdateTaskRequest): Promise<ComplianceTask | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateComplianceTask(arg0, to_candid_UpdateTaskRequest_n24(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateComplianceTask(arg0, to_candid_UpdateTaskRequest_n24(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AirParameter_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AirParameter): AirParameter {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_AirQualityReading_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AirQualityReading): AirQualityReading {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ComplianceTask_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComplianceTask): ComplianceTask {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ComplianceTask]): ComplianceTask | null {
    return value.length === 0 ? null : from_candid_ComplianceTask_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    status: _TaskStatus;
    title: string;
    responsibleOfficer: string;
    createdAt: _Timestamp;
    dueDate: _Timestamp;
    conditionText: string;
    taskType: _TaskType;
    updatedAt: _Timestamp;
    notes: string;
}): {
    id: TaskId;
    status: TaskStatus;
    title: string;
    responsibleOfficer: string;
    createdAt: Timestamp;
    dueDate: Timestamp;
    conditionText: string;
    taskType: TaskType;
    updatedAt: Timestamp;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n15(_uploadFile, _downloadFile, value.status),
        title: value.title,
        responsibleOfficer: value.responsibleOfficer,
        createdAt: value.createdAt,
        dueDate: value.dueDate,
        conditionText: value.conditionText,
        taskType: from_candid_TaskType_n17(_uploadFile, _downloadFile, value.taskType),
        updatedAt: value.updatedAt,
        notes: value.notes
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AirReadingId;
    measuredBy: string;
    value: number;
    date: _Timestamp;
    parameter: _AirParameter;
    createdAt: _Timestamp;
    unit: string;
    notes: string;
    location: string;
}): {
    id: AirReadingId;
    measuredBy: string;
    value: number;
    date: Timestamp;
    parameter: AirParameter;
    createdAt: Timestamp;
    unit: string;
    notes: string;
    location: string;
} {
    return {
        id: value.id,
        measuredBy: value.measuredBy,
        value: value.value,
        date: value.date,
        parameter: from_candid_AirParameter_n7(_uploadFile, _downloadFile, value.parameter),
        createdAt: value.createdAt,
        unit: value.unit,
        notes: value.notes,
        location: value.location
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Overdue: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): TaskStatus {
    return "Overdue" in value ? TaskStatus.Overdue : "InProgress" in value ? TaskStatus.InProgress : "Completed" in value ? TaskStatus.Completed : "Pending" in value ? TaskStatus.Pending : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    EC: null;
} | {
    CTE: null;
} | {
    CTO: null;
}): TaskType {
    return "EC" in value ? TaskType.EC : "CTE" in value ? TaskType.CTE : "CTO" in value ? TaskType.CTO : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    CO: null;
} | {
    NOx: null;
} | {
    SO2: null;
} | {
    PM10: null;
} | {
    PM2_5: null;
} | {
    Other: string;
}): {
    __kind__: "CO";
    CO: null;
} | {
    __kind__: "NOx";
    NOx: null;
} | {
    __kind__: "SO2";
    SO2: null;
} | {
    __kind__: "PM10";
    PM10: null;
} | {
    __kind__: "PM2_5";
    PM2_5: null;
} | {
    __kind__: "Other";
    Other: string;
} {
    return "CO" in value ? {
        __kind__: "CO",
        CO: value.CO
    } : "NOx" in value ? {
        __kind__: "NOx",
        NOx: value.NOx
    } : "SO2" in value ? {
        __kind__: "SO2",
        SO2: value.SO2
    } : "PM10" in value ? {
        __kind__: "PM10",
        PM10: value.PM10
    } : "PM2_5" in value ? {
        __kind__: "PM2_5",
        PM2_5: value.PM2_5
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AirQualityReading>): Array<AirQualityReading> {
    return value.map((x)=>from_candid_AirQualityReading_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ComplianceTask>): Array<ComplianceTask> {
    return value.map((x)=>from_candid_ComplianceTask_n13(_uploadFile, _downloadFile, x));
}
function to_candid_AirParameter_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AirParameter): _AirParameter {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateAirReadingRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateAirReadingRequest): _CreateAirReadingRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateTaskRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTaskRequest): _CreateTaskRequest {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateTaskRequest_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateTaskRequest): _UpdateTaskRequest {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    responsibleOfficer: string;
    dueDate: Timestamp;
    conditionText: string;
    taskType: TaskType;
    notes: string;
}): {
    title: string;
    responsibleOfficer: string;
    dueDate: _Timestamp;
    conditionText: string;
    taskType: _TaskType;
    notes: string;
} {
    return {
        title: value.title,
        responsibleOfficer: value.responsibleOfficer,
        dueDate: value.dueDate,
        conditionText: value.conditionText,
        taskType: to_candid_TaskType_n11(_uploadFile, _downloadFile, value.taskType),
        notes: value.notes
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    measuredBy: string;
    value: number;
    date: Timestamp;
    parameter: AirParameter;
    unit: string;
    notes: string;
    location: string;
}): {
    measuredBy: string;
    value: number;
    date: _Timestamp;
    parameter: _AirParameter;
    unit: string;
    notes: string;
    location: string;
} {
    return {
        measuredBy: value.measuredBy,
        value: value.value,
        date: value.date,
        parameter: to_candid_AirParameter_n3(_uploadFile, _downloadFile, value.parameter),
        unit: value.unit,
        notes: value.notes,
        location: value.location
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TaskStatus;
    notes: string;
}): {
    status: _TaskStatus;
    notes: string;
} {
    return {
        status: to_candid_TaskStatus_n22(_uploadFile, _downloadFile, value.status),
        notes: value.notes
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    EC: null;
} | {
    CTE: null;
} | {
    CTO: null;
} {
    return value == TaskType.EC ? {
        EC: null
    } : value == TaskType.CTE ? {
        CTE: null
    } : value == TaskType.CTO ? {
        CTO: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    Overdue: null;
} | {
    InProgress: null;
} | {
    Completed: null;
} | {
    Pending: null;
} {
    return value == TaskStatus.Overdue ? {
        Overdue: null
    } : value == TaskStatus.InProgress ? {
        InProgress: null
    } : value == TaskStatus.Completed ? {
        Completed: null
    } : value == TaskStatus.Pending ? {
        Pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "CO";
    CO: null;
} | {
    __kind__: "NOx";
    NOx: null;
} | {
    __kind__: "SO2";
    SO2: null;
} | {
    __kind__: "PM10";
    PM10: null;
} | {
    __kind__: "PM2_5";
    PM2_5: null;
} | {
    __kind__: "Other";
    Other: string;
}): {
    CO: null;
} | {
    NOx: null;
} | {
    SO2: null;
} | {
    PM10: null;
} | {
    PM2_5: null;
} | {
    Other: string;
} {
    return value.__kind__ === "CO" ? {
        CO: value.CO
    } : value.__kind__ === "NOx" ? {
        NOx: value.NOx
    } : value.__kind__ === "SO2" ? {
        SO2: value.SO2
    } : value.__kind__ === "PM10" ? {
        PM10: value.PM10
    } : value.__kind__ === "PM2_5" ? {
        PM2_5: value.PM2_5
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
